# Site settings
title: Zhangcun Yan
SEOTitle: Academic and Life Record
header-img: img/university-0.jpg
email: zy221418@gmail.com
description: "The best time for planting one tree is ten years ago, the second time is now."
keyword: "Come on, come on!"
url: "https://yanzhangcun.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/yanzhangcun/yanzhangcun.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you're going to be!"
sidebar-avatar: /img/yanzc.jpg    # use absolute URL, seeing it's used in both `/` and `/about/`

# SNS settings
RSS: false
zhihu_username:       南麓小徒
github_username:      yanzhangcun
# facebook_username:    henry.h.jiang.5
# jianshu_username:   e71990ada2fd
twitter_username:   Yanzc

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important


# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: false    #是否开启Gitalk评论
  clientID: 6a11cab9f46fe57e56a1                            #生成的clientID
  clientSecret: 27ac9ec88d1ecd4c819f7423c95b4ca66e54156a    #生成的clientSecret
  repo:  globien.github.io    #仓库名称
  owner: globien    #github用户名
  admin: globien
  distractionFreeMode: true #是否启用类似FB的阴影遮罩

# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto

# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页


# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true


# 友情链接，请尽量不要删除
Eeveryday: [
    {
        title: "Overleaf",
        href: "https://www.overleaf.com/project"
    },{
        title: "Tongji mail",
        href: "https://mail.tongji.edu.cn/coremail/XT5/index.jsp?sid=EAdSTkbbrFpTYuervVpbDbNxTjShElGj#mail.welcome"
    },{
        title: "Google mail",
        href: "https://mail.google.com/mail/u/0/#inbox"
    },{
        title: "To do list",
        href: "https://tweek.so/fr"
    }
]


# 友情链接，请尽量不要删除
friends: [
    {
        title: "Nicolas",
        href: "http://n.saunier.free.fr/saunier/"
    },{
        title: "Xinyu Chen",
        href: "https://xinychen.github.io/index.html"
    },{
        title: "Google mail",
        href: "https://mail.google.com/mail/u/0/#inbox"
    },{
        title: "Wang Luo",
        href: "https://wangluoangl3.github.io/"
    }
]
